### PR TITLE
Added the base-components repo

### PR DESCRIPTION
**Pull request by steve-ord**
I've added some changes to the base-components repo - that I think mirror your cmake improvements - but the build is not working. The tests cannot find the include files in askap-askap. So not sure whether this is ready to accept. 

the base-components branch is cmake-improvements

### CODE REVIEW

**Comment by steve-ord** [comment]
ok I've fixed the problem the target_include_directories of the applications was not been set -

**Comment by rtobar** [comment]
Merged! I also just checked that I can build base-components correctly locally in the single-project configuration.

BTW, feel free to use a different hosting for this repo, I wouldn't want to become a bottleneck for you if you start making more and more changes.

I could also add a BUILD_COMPONENTS to *not* include base-components in the compilation. Thoughts?

**Comment by steve-ord** [comment]
I think being able to choose the components in general would be good. There are a few applications that do need yandasoft - but do not need the base-repos for example.

**Comment by rtobar** [comment]
OK, I just added it now, it's ON by default

**Pull request merged**
